apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
    namespace: hermes-agent
stringData:
    HERMES_DASHBOARD: ENC[AES256_GCM,data:hw==,iv:rgqcSiDRzcuVF4ELLACRP6rKD2/bUxzqGZVof+flgts=,tag:Xc3AmmHVvPR6ndhL1JKikg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:aa4KhsA=,iv:dc1hRmD/fzLVF/WQZca+wxsxL8J+lsog7/t9vXqYdWY=,tag:24lDOhzmmNf6EGNMVoF9ng==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:RyZBW+l0cQQ76adCLiMR,iv:/7wIIwx7s2VVCOPEesF96WEw1XKcYgocVvDaVWYqTT0=,tag:oWehV9e80cikzAn9KKMxgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVk1FK3lmc25QS1hqS1dO
            WVp4Mzh5cHIwRitvWi9VZDdnM2tUSlo3TUZzCjVnT1RWU1JWUTlCRVNlL1F0RHJk
            MUgzZzBFVFlJU0FqZStCdVRMKzJSM0kKLS0tIGhuQVFSeTNOVmdmZ21mTTlWK3Zs
            VXgrNnRWK21aOFduVHE0a1ZxeFptbDgKJG83JaLZ7IZVIw88HlMyaBaINtBGQvye
            MY8UGf9O8E2H1/KtzPyo4FwJRBfuki5nPn13BzMV6vqKmLkI1/rDgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T21:51:07Z"
    mac: ENC[AES256_GCM,data:2ClwT+I8Lto+NHqb4oLYZ6+Elt2O0Wq3131n2tyu9HAnbJt3H7Ck4l2k9lVymx/VamWAZNzhC2Mc7Z0JZ4Rjwt815hWGwa8zZjNeVRoGh6lOTBb+rqzHRCriZerMovq8ozXZ63naI8OjPbNYajYEeB4OLin3eCZfUGAPNuLYuNg=,iv:77v9XD6xPEXmhpK+CN2A0+kwJg0Z0hScSpDNlDgr8IE=,tag:t/Fmw5OjHzGoE3qObYYWGA==,type:str]
    version: 3.13.1
