apiVersion: v1
kind: Secret
metadata:
    name: git-ssh-key
    namespace: gulfside
stringData:
    ssh: ENC[AES256_GCM,data:L+i/RBnq6zgjh9pgOUelNLULdtLPiw0zwTNu4Zw7ZGuBYckUjoMYgWDXjpunH4Q3myhaTOEZcxUx5dtAaWmdQylbIe5vy0BMHSV7L98IOs4P+fbekIKOkW3vIW3Nbl6qIJ3lMIhtGu+bWV7+Lqz+a2AIVwYmOfQOfPaPB2A2lr7SIuhMKBzBpSKDTRCCxtu/u9reCOkXMD1sBj4kEHvD0sjgsEHu81BvblvZNvmJ9do27aMwDjzira53MQoLUyPsrpJktnZiolJUI42D2xWcUjnz+r1KFzDOGyrS53qs+UvWgQxD3Tl1/ny06HxLcISMsDTzCWHTFmn5PCpgGsHLfQLkXdxd/x92BuTzHNy+WFW+ohKOqlUz1JJ6iXAJrZskBV5h5Ya/jYY5AQfkadECZ/8pNljArWiAO6fw1dY5kErJqSBrWFMNtcNh8iiWQkigYCpnDu+CpKViL2S6uDMOFnk9J4Xu40A8+suxEYJDq5/OAce17Nv4vutamYNpBil7Yrjrl6TDA+vVndi7UrnAFf10HOr44FJOQ/GX,iv:tB0p+xGPsfpE4PxC6SMjW9zm4FFPkdparYwA40Yhtxs=,tag:DWrOyyZEDGRze/h8TCmszg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TENHa2FiVU50ZTVIWDNy
            Ymp2OHRWVEFjK0tlODBId1AraW1qTGhFazIwClQ1Rkg0TWJPNzNvQktUdHRKQ0V2
            ZXlNUjl6U1IrUmtNTFVFb0h1bXBBSHMKLS0tIFdXc0cxaUxINUZUcGVzUzZBYU9u
            cFU5S25hVHBDZWlOVE9SVTVXZTFUam8K3D8S9ImklKy9OG0g1eA5ABQVhm4KYv37
            ykm3orxCL0fQWYRVLxkbf2fX2jxbaRhLB8j43PAIz/tzzLkbIMpogA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:12:21Z"
    mac: ENC[AES256_GCM,data:H9TuyBb4Zg251h2kNB54hVgFeILG7FpM15SHQugp4/m3UYuooGLg5d7r86fLrSwit+cGsgxeC6i+8QggLYk9rO1lIdgxAtYpguv132pxS1ywkVNrsXEDmJnsBwlxC44rzyAsP0cygB7Ak05KPqpn20LamGy91Oy5bp7lf8aINsU=,iv:JxVgMcuq0FfrNK1xAFcvcOvFVLdtViY/i6sHR/ydQ18=,tag:kJnqiHktKJje8zo6sN+Rkw==,type:str]
    version: 3.13.1
