apiVersion: v1
kind: Service
metadata:
  name: gulfside-website
  namespace: gulfside
spec:
  selector:
    app: gulfside-website
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
