apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: homarr-labs
        namespace: homarr
      interval: 12h
  values:
    service:
      enabled: true
      type: ClusterIP
      port: 7575
      targetPort: 7575
    persistence:
      config:
        enabled: true
        size: 1Gi
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 100m
    # Adjust probes for slower startup
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
