apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-agent
  template:
    metadata:
      labels:
        app: hermes-agent
    spec:
      containers:
        - name: hermes-agent
#          image: nousresearch/hermes-agent:v2026.6.19
          image: nousresearch/hermes-agent:latest@sha256:41dad7b20e12f2c9bf920dac56635e1127c95ed1ec2dea41df17e119b5f2c613
          args: ["gateway", "run"]
          ports:
            - containerPort: 8642
            - containerPort: 9119
          envFrom:
            - secretRef:
                name: hermes-agent-secret
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: hermes-agent-data
              mountPath: /opt/data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: hermes-agent-data
          persistentVolumeClaim:
            claimName: hermes-agent-data
