apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: linkding
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
        - image: cloudflare/cloudflared:latest
          name: cloudflared
          command:
            - cloudflared
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            - run
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared
              readOnly: true
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: cloudflared
        - name: credentials
          secret:
            secretName: tunnel-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: linkding
data:
  config.yaml: |
    tunnel: f7897851-6b1b-48af-9490-7739f9f17863
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - hostname: lds.toddpillars.com
        service: http://linkding.linkding.svc.cluster.local:9090
      - hostname: abs.toddpillars.com
        service: http://audiobookshelf.audiobookshelf.svc.cluster.local:3005
      - service: http_status:404
