apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: apps
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/controllers/staging
  prune: true
