apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postiz.fullname" . }}-config
  labels:
    {{- include "postiz.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if eq $key "TEMPORAL_ADDRESS" }}
  {{ $key }}: {{ include "postiz.temporalAddress" $ | quote }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}