apiVersion: v1
kind: Secret
metadata:
    name: postiz-postgres
    namespace: postiz
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:G+MpB2NCCQwT1YmjH89MYsjPXFCLbMzzTxATI0qerWGcSrexSgqFV9603Z+UeZZq,iv:x8TuQv76afIiSPKHgjWCUy6nhI3f/hfDy/1eXlEVqrU=,tag:BB7mFq9Ny1nbJYgRWdTRIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzclJZeS9UaEc0ckwrOTRr
            QTd6UWtMK3lnZXczOFNxZk9hbkdwV0poVmpZCmJjRjlkSDJaanIwRzRXOThnWlF1
            SEM4OTNaRWxOV2MzRDluNWpnZFZyRUUKLS0tIFlGREdLVlpxcy9mNjBoWkkrRVMv
            VG9qWnRTZGhCMkRwYm82TnYyZWttM2sKFbjV89U24MM39FlAWXuP1WPdiBtuelpJ
            /LD0ZJtCGBvTdAJeTAkIvwx7mzdyRo126dKsOxjCqQYw2l2suIsb9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T17:12:48Z"
    mac: ENC[AES256_GCM,data:aObkbzzmqwgNbMsYYXgdMXNBjCHIOljUaVoRtotii4vaLJdJ2pYCiPRWlLWkAQR4UfrCQHFnIoaSiMtK1qtZksJMR9oU5dMCHBdHLxjkKswmhsVFa8hybL1wmN/DyBx2YguJTwVebP5Pq+eXSiY2mdS1ZaK+d/dsDfmcdCpunyE=,iv:nXdKsiHEugK8x3Xz8tEBGIofDmEFGoLBuJr5DwZwMqA=,tag:s3zuTcV7QlfrrEDMUG5h+w==,type:str]
    version: 3.13.2
