apiVersion: v1
kind: Secret
metadata:
    name: postiz-secrets-ext
    namespace: postiz
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:CnAq/DDeaMRZJiuUQJG4KdbMpFp/QJpy6eDLzpWf3vk9vqPml4t51jOFfC5+EnicauL3KZ5e1w1mku/jrc1/qOLq7b3aSAuOjc65rNVRD6W7zil3bTsDR1WtANgL37CE,iv:YoxAlgBVmN5rxjwrumJEFVI7BbWnWLw6E7pmGJIf3O0=,tag:5brirJeDHNAAHzhLEuXxoA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:+UMeY1doVIPb9V55kMseIJtiBgSaYALUlg==,iv:gTd0+d3fK8PLfkOi+iLI6yXCzpFEgxu3sEwyWT/x2bI=,tag:6kDj0WNc0ViZ4aGT44VtcQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:FJsjZSzPyHmXapX3ujP9mtUD126eJm+9rV6No/apc5FVxReEgq2jOtpgXdy3pJPlNM8AUNW6VzFqBG8SsxFaHpzsZDzayOrzYS/jz0M7mpMgoYPdAnXygTYv8vkxFfNq,iv:b4tXqDAgNaE5+TlRJBrjRY1iiAP446mzAyoi6nh4t7U=,tag:jmJHKcIkWNfFe1F1L/4w2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TVlBZVpubGZwK2JqUE9j
            QjZjM3kxZHBPcHV0MjhtTkJUTDhiVzRzZ0h3CkZac3NIQm9WeFBZTnRWNGVraG9C
            Q01Dall2VnZnSUllMHpEYlZBbFMrZW8KLS0tIDJFbDBSKzZNSUpKZ1VUOEExWmNa
            NjkzUFpEQktqWVc0SGJqZjFNNTJZMDQKAVATKtKen1WaXm+x126Y1Kz7yrIVxTFW
            YUWN/rL8YRJjbCSRIBHImFRXjT/PdEU1V3l60RLkMoUpx1T9EH+dtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T17:12:48Z"
    mac: ENC[AES256_GCM,data:msl+TDD/3stVxOYgUxREfsX4IxDSRutJUEb+BL1Sm9HlNH9Wgw69xC05su3aebdhSZQl08OmJ+bIkmzW+PgJU3T7PfO+SLQqqXY46tt7MJjOXx9aBe6oMGgl8iX7zTXUutqXI/b9q7pANA49LaGu6FDa/+FzarqReIjqwZbuvJU=,iv:ulSXjv8QltE+LUOz44h2mgY8i5o3vXvhEPl+KThc7VI=,tag:ByfsKj7XMwEbyA4GjHz7pg==,type:str]
    version: 3.13.2
