apiVersion: v1
kind: Secret
metadata:
    name: n8n-garage-secret
    namespace: naten
type: Opaque
stringData:
    GARAGE_S3_ENDPOINT: ENC[AES256_GCM,data:sJIstNnlQZhOHkctrH2blhUM8qWFlMm2L6c=,iv:yGU2t4uTeIDOKvVjRjKpjtOYi64TJ82mRB9zAGrP804=,tag:Ztpo1iraQOHiL5ZvA/xIFg==,type:str]
    GARAGE_S3_REGION: ENC[AES256_GCM,data:sX4Sq5hw,iv:NKo/R2qMOX2jHrWan6+xb94J8GZLilG4ip8gQsxfrec=,tag:bVlpaRBp6ZOHuLkPG1RLag==,type:str]
    GARAGE_S3_BUCKET: ENC[AES256_GCM,data:4OYQ+XYfGnM=,iv:epU5E7zVcVz8UF5310rFs+VnSHf2+UitXJpidTzQK4U=,tag:nzkYayEvEg2HqUYq5XB/oQ==,type:str]
    GARAGE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:Edv9tqYPvuEUjvJkKuTrWRdCUW5brdnIdQ4=,iv:7dRr6G2+u0tsEHebkULljHnDL/WsY61yeLQGlYa+4CM=,tag:rhU6JUBkyTPPeOCMNq8kkw==,type:str]
    GARAGE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s2QYOHiEy05W55HOz3f78kjVjMT0kqnnalF0bxSyxJvq6+VpfN+zFcwZNofKqlVfd/g8FgfAwkZFn1Rl7t8Q6g==,iv:J1sybnPGnBZU0MOpAAn60WfXc2DFYYVD2n3mtqeZ+/Y=,tag:TomIfeQ6RqFOzEGCbx64/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUVMzRjB4RUxLanE4YlBV
            WTZDbC9hSlJTYitlNWN5UWlCdTh1SXd1N2hFCldmSm9WRkptanZma2tldFl6b2lP
            WWtJSmYrdjRpelJjZDhLU3I1TlZ2Y1EKLS0tIG5sY2poaDYybVZ6V0VzRldFZ2tC
            N0p1eENxdVF1MlFKNXVQUkJYR2g3TzgK0kunFkGIE4QLbqoJDZaGmL3/F68sPdu6
            PFyFXLCFvUp//KtrSS8hvpvZRlng8yEMLLqV0QCVBuyQ9MHmEWsSZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T14:54:06Z"
    mac: ENC[AES256_GCM,data:2iERMDH9aCmp3VqCa7mEY7E2aI89j3AdTXfWuxKn6XRA+iO3RsDEoxA80ND6lu9J4b51xZ/9QwSCNxXTXzb7i8fWKx5PFu0UMI6/s1jfFJpU6v993Sn9COPR78t/W7oIyZ90KzVS5I1W90Bf7IvsKs2ziPLF4jX9JWo98UsmV1c=,iv:EMekcU9yszIQo8iuNtbmDcImiF4bap7pOJKB5BjhxKE=,tag:Ib5EK7MpkQt4lCoEnKYbxw==,type:str]
    version: 3.13.3
