apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 10m
  chart:
    spec:
      chart: open-webui
      version: 10.2.1
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      interval: 10m
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - http://192.168.0.36:11434
    persistence:
      enabled: true
      storageClassName: local-path
      accessMode: ReadWriteOnce
      size: 5Gi
