apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:jDpt8oHMWYLdLmjWGd+oq1iJsf0B+EbpLfoLg1ShGYRkW36j2obKv+wn4UvROY+QJXZIiESLKd9CY9xP+OUIyDJvj3SP0fyZegHBhEkeEiY1Uk5p2f8plp1GSV0D31wRwJ0EydVMz2vPYGnBU2aYI6/8lcuu4JpeBWYrojFnjH1i43/yKmCnYbv2YF/w3H5yLzEukE8OznYye87APoi9fV3zERwsx4YEcRpEIaUO/H9brxZ5,iv:XO41uxJoCtbiFEi6Lds05PmnU6lCkLuC/dgD6oF0Zr0=,tag:mILXbVt1/iiYB2xeRhiEUQ==,type:str]
sops:
    age:
        - recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbWxSdGJKcSs1Y3ZIenN3
            L3l5aFduNi9HWEF0UTllaExkalIzVzZac2xRClExMjVjQ2wvY3pwSVNZME12Ujdx
            T3pBaUNKYVM5SWRNOUowRXRrQ01nV00KLS0tIFRxUkJHYjMyL0xqaFptd1BuWE1i
            OXVMVVBabGdyNWlsK0pRd0ptVE8wRUEKaKv/r8xKuXS0isATi1a021dqoGcLAMh2
            1aXSNC1ntCkfa/7ftRQmNl6K/Yh4Nz/mVxgW0O0peci26aWJOTlsLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:05:26Z"
    mac: ENC[AES256_GCM,data:CmxGPFfN55I/hE9YbBXhieiVlgPePacF50VhLkzcQ/m+BX95hYfMoZEZO4+gHVSgGNH3cbdl3yCX/ZTgVaxSNm0L571bYwwJrhpiqPUlc7/RU8CvCpaerImuoeNVwaLGfhbcLfzEnW5ApbJnk3O7XCKRRpKV7ep8KaSnFyxmDdE=,iv:AFVfSEY7J6ewmehvJjbHwrhMI3QQp+5rIq/aRKdQq4g=,tag:do4CbXDZus2v8MoZnx0ixQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
